"""Add channel field to signals table.

Revision ID: 20260526_0002
Revises: 20260526_0001
Create Date: 2026-05-26 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20260526_0002"
down_revision = "20260526_0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("signals", sa.Column("channel", sa.String(), nullable=False, server_default="news"))
    op.create_index(op.f("ix_signals_channel"), "signals", ["channel"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signals_channel"), table_name="signals")
    op.drop_column("signals", "channel")
    # ### end Alembic commands ###
